name: getup_early_onemin
description: getup_early_onemin

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.7+8

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^2.0.1
  provider: ^6.0.3
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.10.0
  just_audio: ^0.9.30
  file_picker: ^5.2.0
  path_provider: ^2.0.11
  intl: ^0.17.0
  material_design_icons_flutter: 5.0.6996
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite: ^2.0.3+1
  flutter_local_notifications: ^9.8.0+1
  android_alarm_manager_plus: ^2.1.0
  flutter_lints: ^2.0.0
  date_format: ^2.0.4
  device_info: ^2.0.3
  http: ^0.13.4
  rxdart: ^0.27.3
  flutter_native_timezone: ^2.0.0
  fluttertoast: ^8.0.8
  flutter_picker: ^2.0.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
flutter:
  generate: true

  uses-material-design: true
  assets:
    - assets/alarm.mp3
    - assets/assets_setting.db
    - assets/icon/



